### ISSUE TITLE
Move away from `console_script` entrypoints

### ISSUE THREAD

**Issue by jhkennedy** [ASFHyP3/hyp3-cookiecutter#10]
Inthe past, we've created command line (`console-script`) entrypoints for hyp3 plugins, making a "hyp3" entry point(s), and a "science" entry point which has more available options. For example, in hyp3-gamma:
* the main "HyP3" entrypoint: https://github.com/ASFHyP3/hyp3-gamma/blob/develop/setup.py#L61
  which can also be called on the command line like `python -m hyp3_gamma`
* The HyP3 RTC entry point: https://github.com/ASFHyP3/hyp3-gamma/blob/develop/setup.py#L62
  which can also be called on the command line like `python -m hyp3_gamma ++process RTC`
* the "Science" HyP3 RTC entry point: https://github.com/ASFHyP3/hyp3-gamma/blob/develop/setup.py#L63
  which is just a general RTC workflow script not tied to HyP3

For this cookiecutter: 
1. we don't need to register any HyP3 console script entry points as the hyp3 entry points are already accessible on the command line via `python -m`
2. we don't need to register extra "science" entry points as this is a cookie cutter intended to help you develop a hyp3-plugin, and not every plugin will need a CLI version of the "science" code (e.g., "scientists" may prefer jupyter notebooks and not use the command line at all)

Accordingly, I believe we can: 
-  [x] drop these lines in the `pyproject.toml`: https://github.com/ASFHyP3/hyp3-cookiecutter/blob/update_staging/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml#L29-L32
- [x] drop the `process_name` test: https://github.com/ASFHyP3/hyp3-cookiecutter/blob/update_staging/%7B%7Bcookiecutter.project_name%7D%7D/tests/test_entrypoints.py#L6-L8
- [x] update the `package_name` test to invoke the package `__main__` entry point like `python -m {{cookiecutter.package_name}} -h`

**Comment by jtherrmann** [comment]
Relates to https://github.com/ASFHyP3/hyp3-cookiecutter/issues/9
