### ISSUE TITLE
Need better documentation on how to set permissions for `GITHUB_PAK`

### ISSUE THREAD

**Issue by forrestfwilliams** [ASFHyP3/hyp3-cookiecutter#23]
In order to get the CI/CD working correctly, the user of the cookiecutter will need to create a Personal Access Token with a certain set of permissions. We should document:

1. Which type of access token they should create (Classic or Fine-Grained) - *I believe the answer is Classic*?
2. What is the minimal set of boxes in the screenshot below that need to be checked in order for the actions to work?

<img width="593" alt="Screen Shot 2023-03-20 at 9 25 51 AM" src="https://user-images.githubusercontent.com/31411324/226370080-ca7e5172-441d-45d7-9230-8ac14bab2f53.png">

**Comment by forrestfwilliams** [comment]
@jhkennedy and @jtherrmann I'd enjoy hearing your thoughts on this one.

**Comment by jtherrmann** [comment]
Maybe try checking what perms are available to `tools-bot`: https://github.com/orgs/ASFHyP3/people/tools-bot (if possible)

**Comment by jtherrmann** [comment]
`tools-bot` has a classic token with these perms:

![tools-bot-token-perms](https://user-images.githubusercontent.com/19476938/226475577-c2db2afe-7765-47fd-82a3-87bebf3102dc.png)

**Comment by forrestfwilliams** [comment]
Here's the new screenshot (in two pieces)
<img width="860" alt="Screen Shot 2023-03-24 at 8 08 00 AM" src="https://user-images.githubusercontent.com/31411324/227529461-9575c389-e1ce-491b-a7ec-a02421127260.png">

**Comment by forrestfwilliams** [comment]
<img width="933" alt="Screen Shot 2023-03-24 at 8 09 09 AM" src="https://user-images.githubusercontent.com/31411324/227529691-f8a840c6-800d-4865-80f7-b40f3f706bf1.png">

**Comment by jacquelynsmale** [comment]
@forrestfwilliams and I ran into this issue (or a similar issue) running `hyp3-cookiecutter` to create `hyp3-back-projection`. We missed updating `$GITHUB-PAK`, and had to go back to fix it. Could this be included as a variable in the `cookiecutter.json` file, rather than hardcoding it to be `$GITHUB-PAK`?

**Comment by jhkennedy** [comment]
Looks like @forrestfwilliams did in https://github.com/ASFHyP3/hyp3-cookiecutter/pull/31, but we never closed the issue

**Comment by forrestfwilliams** [comment]
Looks like I should have read my own documentation 😭!
