### ISSUE TITLE
Is it possible to create a plugin in a different github organization for plugins?

### ISSUE THREAD

**Issue by cmarshak** [ASFHyP3/hyp3-cookiecutter#4]
Want to push to a research Github organization managed by @dbekaert.

**Comment by jhkennedy** [comment]
Hi @cmarshak, the answer is yes, but with work. 

Currently this repo is setup with the assumption it'll be in our organization. However, that assumption is mostly in the CI/CD, metadata, and community parts (code of conduct, etc). The actual functional python and docker code doesn't really care who/where it's run. 

You can probably get it pretty quickly functional by dropping the AWS ECR parts and only packaging to the GitHub container registry. On the HyP3 side (at least for an ASF managed HyP3) we'll want to pull the container from the GitHub container registry just to keep the plugin code and container together (but could pull from any registry we're given access too). Or, just ignore the CI/CD parts for now and manually build and push.

I've got a branch going where I'm reworking this to have multiple cookiecutters and docs for external plugins, I just haven't had a chance to finish it up. If you're interested in making a HyP3 plugin, I'd propose we set up a mini hackathon when I'm back from vacation (Aug. 30) and get an external one going.

**Comment by cmarshak** [comment]
Ok - let's talk when you return. I am eager to learn more - have plenty to do in the interim docker-izing the ISCE2 processing and removing some extraneous code.

**Comment by jhkennedy** [comment]
We've picked this up again and the next cookie-cutter release will be generalized for anyone to use it, and host the plugin repo in any user/org

**Comment by jhkennedy** [comment]
This was generally resolved in v0.1.0; closing.
