### ISSUE TITLE
Need to update Actions

### ISSUE THREAD

**Issue by forrestfwilliams** [ASFHyP3/hyp3-cookiecutter#6]
Prior to creation of the ISCE2 plugin, we would like to update the GitHub Actions to the latest version. Here is a list of all the reusable actions from `ASFHyP3/actions`:

- [x] reusable-bump-version.yml
- [x] reusable-changelog-check.yml
- [x] reusable-docker-ghcr.yml
- [x] reusable-flake8.yml
- [x] reusable-labeled-pr-check.yml
- [x] reusable-pytest.yml
- [x] reusable-release-checklist-comment.yml
- [x] reusable-release.yml
- [x] reusable-secrets-analysis.yml
- [x] dependabot.yml

**Comment by jhkennedy** [comment]
We'll also want to add a dependabot yaml to keep these actions up to date. E.g.: 
https://github.com/ASFHyP3/hyp3-autorift/blob/develop/.github/dependabot.yml

(maybe not daily though?)
